---
# Source: tempo/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tempo
  namespace: monitoring
  labels:
    helm.sh/chart: tempo-1.25.0
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/version: "2.9.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
