- name: Install package
  hosts: all
  become: true

  vars_prompt:
    - name: package
      prompt: Package
      private: false
    - name: state
      prompt: State
      default: present
      private: false

  tasks:
    - name: Install '{{ package }}'
      ansible.builtin.apt:
        name: "{{ package }}"
        state: "{{ state }}"
