validationFailureAction: Enforce

policyExclude:
  disallow-capabilities:
    any:
      - resources:
          kinds:
            - Pod
          namespaces:
            - kube-system
            - longhorn-system
            - monitoring

  disallow-host-namespaces:
    any:
      - resources:
          kinds:
            - Pod
          namespaces:
            - kube-system
            - longhorn-system
            - monitoring

  disallow-host-path:
    any:
      - resources:
          kinds:
            - Pod
          namespaces:
            - longhorn-system
            - kube-system
            - monitoring
            - system-upgrade

  disallow-host-ports:
    any:
      - resources:
          kinds:
            - Pod
          namespaces:
            - kube-system
            - monitoring

  disallow-privileged-containers:
    any:
      - resources:
          kinds:
            - Pod
          namespaces:
            - longhorn-system
            - kube-system

  disallow-selinux:
    any:
      - resources:
          kinds:
            - Pod
          namespaces:
            - kube-system

  restrict-apparmor-profiles:
    any:
      - resources:
          kinds:
            - Pod
          namespaces:
            - kube-system

  restrict-seccomp:
    any:
      - resources:
          kinds:
            - Pod
          namespaces:
            - kube-system
