admissionController:
  container:
    resources:
      requests:
        cpu: 10m
        memory: 80Mi
  serviceMonitor:
    enabled: true

backgroundController:
  resources:
    requests:
      cpu: 10m
      memory: 80Mi
  serviceMonitor:
    enabled: true

cleanupController:
  resources:
    requests:
      cpu: 10m
      memory: 60Mi
  serviceMonitor:
    enabled: true

reportsController:
  resources:
    requests:
      cpu: 10m
      memory: 120Mi
  serviceMonitor:
    enabled: true
