apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-traefik
  namespace: kube-system
spec:
  valuesContent: |-
    providers:
      kubernetesIngress:
        allowCrossNamespace: true
        publishedService:
          enabled: false
      kubernetesGateway:
        enabled: true
    resources:
      requests:
        cpu: 25m
        memory: 100Mi
    priorityClassName: system-cluster-critical
    ports:
      traefik:
        hostPort: 8080
      web:
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
              permanent: true
      websecure:
        http:
          middlewares:
            - kube-system-rate-limit@kubernetescrd
            - kube-system-compress@kubernetescrd
    ingressRoute:
      healthcheck:
        enabled: true
        matchRule: PathPrefix(`/health`)
    metrics:
      prometheus:
        serviceMonitor:
          enabled: true
    additionalArguments:
      - "--providers.kubernetesingress.ingressendpoint.ip=127.0.0.1"
