apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-infra-root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Nasus20202/infra.git
    targetRevision: main
    path: kubernetes/oci/compute/cluster/argocd-apps
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
