apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  sources:
    - repoURL: https://kubernetes-sigs.github.io/descheduler
      chart: descheduler
      targetRevision: "0.33.0"
      helm:
        valueFiles:
          - $values/kubernetes/oci/compute/cluster/descheduler/values.yaml
    - repoURL: https://github.com/Nasus20202/infra.git
      targetRevision: main
      ref: values
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
