apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: "6.36.0"
      helm:
        releaseName: loki
        valueFiles:
          - $values/kubernetes/oci/compute/cluster/monitoring/loki-values.yaml
    - repoURL: https://github.com/Nasus20202/infra.git
      targetRevision: main
      ref: values
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
