apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  sources:
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: "1.10.0"
      helm:
        valueFiles:
          - $values/kubernetes/oci/compute/cluster/longhorn/values.yaml
    - repoURL: https://github.com/Nasus20202/infra.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/Nasus20202/infra.git
      targetRevision: main
      path: kubernetes/oci/compute/cluster/longhorn/recurringjob
  destination:
    name: in-cluster
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
