---
# Source: kube-prometheus-stack/templates/prometheus/serviceaccount-token-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-kube-prometheus-prometheus-token
  namespace: monitoring
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/name: kube-prometheus-stack-prometheus
    app.kubernetes.io/component: prometheus
    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/version: "90.1.2"
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-90.1.2
    release: "prometheus"
    heritage: "Helm"
  annotations:
    kubernetes.io/service-account.name: prometheus-kube-prometheus-prometheus
type: kubernetes.io/service-account-token

