apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: filesystem-trim
spec:
  concurrency: 1
  cron: 0 1 * * *
  groups:
    - default
  name: filesystem-trim
  retain: 0
  task: filesystem-trim
