crds:
  enabled: true

featureGates: "ACMEHTTP01IngressPathTypeExact=false"

resources:
  requests:
    cpu: 10m
    memory: 50Mi
  limits:
    memory: 150Mi

cainjector:
  resources:
    requests:
      cpu: 10m
      memory: 50Mi
    limits:
      memory: 150Mi

webhook:
  resources:
    requests:
      cpu: 10m
      memory: 50Mi
    limits:
      memory: 150Mi
