apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    kubeProxyReplacement: true
    k8sServiceHost: 10.0.1.50
    k8sServicePort: 6443
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
