apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      allowSnippetAnnotations: true
      config:
        use-forwarded-headers: true
        enable-real-ip: true
        forwarded-for-header: proxy_protocol
        annotations-risk-level: Critical
        use-gzip: true
        gzip-level: "5"
        gzip-types: |
          text/plain
          text/css
          text/javascript
          application/javascript
          application/json
          application/xml
          application/rss+xml
          application/atom+xml
          application/x-javascript
          application/x-httpd-php
          application/xhtml+xml
          application/x-font-ttf
          application/x-font-opentype
          application/vnd.ms-fontobject
          image/svg+xml
          image/x-icon
          font/opentype
          font/ttf
          font/otf
          font/woff
          font/woff2
      extraArgs:
        enable-ssl-passthrough: true
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
