apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
spec:
  sourceRepos:
    - "https://github.com/Nasus20202/infra.git"
    - "https://argoproj.github.io/argo-helm"
    - "https://charts.jetstack.io"
    - "https://grafana.github.io/helm-charts"
    - "https://prometheus-community.github.io/helm-charts"
    - "https://charts.longhorn.io"
    - "https://kyverno.github.io/kyverno/"
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
