service:
  type: ClusterIP

tls:
  force: true

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  hosts:
    - host: portainer.nasus.dev
      paths:
        - path: /
  tls:
    - hosts:
        - portainer.nasus.dev
      secretName: portainer-tls

persistence:
  size: 1Gi
