---
# Source: k8s-monitoring/charts/autoInstrumentation/charts/beyla/templates/cache-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beyla-k8s-cache
  namespace: monitoring
  labels:
    helm.sh/chart: beyla-1.11.0
    app.kubernetes.io/name: beyla-k8s-cache
    app.kubernetes.io/instance: k8s-monitoring
    app.kubernetes.io/version: "2.8.4"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: beyla
    app.kubernetes.io/component: workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: beyla-k8s-cache
  template:
    metadata:
      labels:
        helm.sh/chart: beyla-1.11.0
        app.kubernetes.io/name: beyla-k8s-cache
        app.kubernetes.io/instance: k8s-monitoring
        app.kubernetes.io/version: "2.8.4"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: beyla
    spec:
      serviceAccountName: k8s-monitoring-beyla
      containers:
        - name: beyla-cache
          image: docker.io/grafana/beyla-k8s-cache:2.8.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50055
              protocol: TCP
              name: grpc
          resources:
            limits:
              cpu: "3.0"
              memory: 100Mi
            requests:
              cpu: "0.1"
              memory: 50Mi
          env:
            - name: BEYLA_K8S_CACHE_PORT
              value: "50055"
