cluster:
  name: compute-k8s

destinations:
  - name: loki
    type: loki
    url: http://loki:3100/loki/api/v1/push
  - name: prometheus
    type: prometheus
    url: http://prometheus-kube-prometheus-prometheus:9090/api/v1/write

clusterEvents:
  enabled: true
  collector: alloy-logs

nodeLogs:
  enabled: true
  collector: alloy-logs

podLogs:
  enabled: true
  collector: alloy-logs
  structuredMetadata:
    pod: pod

applicationObservability:
  enabled: false

autoInstrumentation:
  enabled: false

# Collectors
alloy-singleton:
  enabled: false

alloy-metrics:
  enabled: false

alloy-logs:
  enabled: true
  alloy:
    mounts:
      varlog: true
    resources:
      requests:
        cpu: 30m
        memory: 150Mi
      limits:
        memory: 300Mi

alloy-profiles:
  enabled: false

alloy-receiver:
  enabled: false

alloy-operator:
  crds:
    deployAlloyCRD: true
  resources:
    requests:
      cpu: 20m
      memory: 50Mi
    limits:
      memory: 100Mi
