apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policy-reporter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  sources:
    - repoURL: https://kyverno.github.io/policy-reporter/
      chart: policy-reporter
      targetRevision: "3.4.2"
      helm:
        releaseName: kyverno-policy-reporter
        valueFiles:
          - $values/kubernetes/oci/compute/cluster/kyverno/kyverno-policy-reporter-values.yaml
    - repoURL: https://github.com/Nasus20202/infra.git
      targetRevision: main
      ref: values
  destination:
    name: in-cluster
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
