- op: replace
  path: /spec/template/spec/containers/0/resources
  value:
    requests:
      cpu: 10m
      memory: 100Mi
- op: add
  path: /spec/template/spec/priorityClassName
  value: system-cluster-critical
